[phases.setup]
nixPkgs = ['nodejs_20', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node build'

[variables]
NODE_ENV = 'production'