name = "enterprise-ai-adoption-hub"
compatibility_date = "2025-01-23"

# Pages configuration
pages_build_output_dir = ".svelte-kit/cloudflare"

# Environment variables (if needed for runtime)
[vars]
NODE_VERSION = "20"