name = "enterprise-ai-adoption-hub"
compatibility_date = "2025-01-23"

# This is required for the SvelteKit Cloudflare adapter
main = "./.svelte-kit/cloudflare/_worker.js"

# Static assets configuration
[assets]
directory = "./.svelte-kit/cloudflare"
binding = "ASSETS"

# Build configuration
[build]
command = "npm run build"

# Environment variables
[vars]
NODE_VERSION = "20"